# Generated by Django 2.2.7 on 2019-12-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20191213_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='photo_1',
            field=models.ImageField(blank=True, default='photos/h.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='flats',
            name='photo_2',
            field=models.ImageField(blank=True, default='photos/h.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='flats',
            name='photo_3',
            field=models.ImageField(blank=True, default='photos/h.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
