# Generated by Django 2.2.7 on 2019-12-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20191213_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='photo_1',
            field=models.ImageField(blank=True, default='media/h.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='flats',
            name='photo_2',
            field=models.ImageField(blank=True, default='media/h.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='flats',
            name='photo_3',
            field=models.ImageField(blank=True, default='media/h.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
